cmake -S . -B build \
    -DCMAKE_CXX_COMPILER=/lore/mersoj2/laces-software/build/rhel9/ADA89/kokkos/install/bin/nvcc_wrapper \
    -DCMAKE_BUILD_TYPE=Debug \
    -DBUILD_SHARED_LIBS=OFF \
    -DOmega_h_ROOT=/lore/mersoj2/laces-software/build/rhel9/ADA89/omega_h/install \
    -Dpcms_ROOT=/lore/hasanm4/wsources/dg2xgcDeps/build/pcms/ADA89/pcms/install \
    -Dperfstubs_DIR=/lore/mersoj2/laces-software/build/rhel9/perfstubs/install/lib64/cmake/ \
    -Dredev_DIR=/lore/mersoj2/laces-software/build/rhel9/ADA89/redev/install/lib64/cmake/redev/ \
    -DKokkos_ROOT=/lore/mersoj2/laces-software/build/rhel9/ADA89/kokkos/install/ \
    -DCatch2_ROOT=/lore/mersoj2/laces-software/build/rhel9/Catch2/install \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
